BomiGroup_service_lookup = {
    "1 MAN 30 MINUTES STANDARD": "M30S",
    "1 MAN 30 MINUTES EXPRESS": "M30E",
    "1 MAN 1 HOUR STANDARD": "1MHS",
    "1 MAN 1 HOUR EXPRESS": "1MHE",
    "2 MAN 1 HOUR STANDARD": "2MHS",
    "2 MAN 1 HOUR EXPRESS": "2MHE",
    "4 MAN 2 HOUR STANDARD": "4MHS",
    "4 MAN 2 HOUR EXPRESS": "4MHE",
    "30 MINUTES STANDARD": "30MS",
    "30 MINUTES EXPRESS": "30ME"
}

