DHL_NXP_HKG_City_CrossRef = {
    "HKG": "HONG KONG",
    "SIN": "SINGAPORE",
    "LAX": "LOS ANGELES",
    "BTS": "IVANKA",
    "BKK": "BANGKOK",
    "BUD": "BUDAPEST",
    "IST": "ISTANBUL",
    "NRT": "NARITA",
    "ICN": "INCHEON"
}

DHL_NXP_HKG_Cargo_CrossRef = {
    "HK Domestics Distribution from Other Local Delivery": "LTL",
    "HK Domestics Distribution from Local Cargo Collection": "LTL",
    "HK Domestics Distribution from APG": "LTL",
    "HK Domestics Distribution from SMO": "LTL",
    "HK Domestics Distribution from Local Forwarder": "LTL",
    "HK Domestics Distribution from RDC": "LTL",
    "FOB shipments to customer appointed forwarders": "LTL",
    "HK Domestics Distribution from GDC": "LTL"
}

DHL_NXP_HKG_Service_CrossRef = {
    "GDC Inbound (Sub-contractor)": "AIR",
    "Return shipment (RMA)": "AIR",
    "HK Domestics Distribution from GDC": "LOC",
    "EQS": "EXP",
    "DD9": "AIR",
    "DA2": "AIR",
    "DD2": "AIR",
    "DA1": "AIR",
    "DD1": "AIR",
    "Truck - Local trucking charge from MTL to RDC Monthly fixed charges": "TL",
    "HK Domestics Distribution from Other Local Delivery": "LOC",
    "HK Domestics Distribution from Local Cargo Collection": "LOC",
    "HK Domestics Distribution from APG": "LOC",
    "HK Domestics Distribution from SMO": "LOC",
    "HK Domestics Distribution from Local Forwarder": "LOC",
    "HK Domestics Distribution from RDC": "LOC",
    "FOB shipments to customer appointed forwarders": "LOC",
    "One stop delivery (monthly fixed chg) for HKG": "DDL",
    "RDC Inbound (Sub-contractor)": "AIR",
    "Outbound shipment": "AIR"
}

DHL_NXP_HKG_Accessorials_lookup = {
    "Pick-up charge ( per kg)(CTG)": "PUC",
    "Airport terminal handling at origin (per kg)(THC)": "TERO",
    "Customs clearance at origin(360)": "360O",
    "Clerical handling at origin (per shipment) (HDC)": "HHBO",
    "Pick-up charge ( per kg)(OFC)": "PUC",
    "Fuel surcharge (per kg) (FUE)": "FUE",
    "Security surcharge (per kg) (SEF)": "SEF",
    "TOL fee (TOL)": "TOL",
    "Delivery charge (DEL)": "DEL",
    "Bonded Truck charge (BON)": "BON",
    "Special delivery(685)": "SPD",
    "Handling(HHB)": "998",
    "Overtime(OAC)": "OAC",
    "Airwaybill fee (MWB)": "MWB",
    "Storage charge (STR)": "STR",
    "IAC Security (IAC)": "IAC",
    "Termianl Security charge (TES)": "TES",
    "Automated (365)": "370",
    "TSA (TERO)": "TERO",
    "ICS/AMS (ICS)": "AMS",
    "DET (ACR)": "ACR",
    "HK1 (PUC)": "PUC",
    "TUC (CDCG)": "CDCG",
    "MAA (586)": "586",
    "ICI (QIF)": "QIF",
    "DES (TERD)": "TERD",
    "DHF (HHBD)": "HHBD",
    "EXCEPTION (999)": "999",
    "DESTINATION CCC (DCF)": "360D",
    "DTE": "DTE",
    "360D": "360D",
    "DVA(260)": "260",
    "CROSS DOCK (CDCG)": "CDCG",
    "TRANSFER CHARGE (TRF)": "TRF",
    "HANDLING CHARGE (HDC)": "HDC",
    "DECLARED VALUE CHARGE (DVC)": "DVC",
    "CONTAINER FREIGHT STATION CHARGE (CFS)": "CFS",
    "EXPORT PROCESSING (EXTG)": "EXTG",
    "DOCUMENTATION CHARGE (DOC)": "DOC",
    "PICKUP CHARGES (PUC)": "PUC",
    "TERMINAL CHARGE (TER)": "TER",
    "EXPORT DOCUMENTATION CHARGE (EDF)": "EDF",
    "PORT SECURITY FEE (PSF)": "PSF",
    "ENTRY FEE (ENT)": "ENT",
    "BUNKER ACCESSORIAL FEE (BAF)": "BAF",
    "CURRENCY ADJUSTMENT FACTOR (CUF)": "CUF",
    "PEAK SEASON SURCHARGE (PKC)": "PKC",
    "X-RAY CHARGE (762)": "762",
    "FORWARDING FEE (FOR)": "FOR",
    "Japan Overpack Destination breakbulk charg (BBK)": "BBK",
    "Origin Manpower Charge (OHC)": "OHC",
    "Miscellaneous Outlays(MSO)": "MSO",
    "On Call Pickup Surcharge(540)": "540",
    "WAREHOUSE/HANDLING CHARGE (WHC)": "WHC"
}

DHL_NXP_HKG_Tax_lookup = {
    "JAPAN VAT TAX (DTX)": "DTS",
    "VAT(750)": "VAT"
}